image: debian/stretch

test:
  script:
  - apt-get update -qy
  - apt-get install -y default-libmysqlclient-dev python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 manage.py test
