# Generated by Django 2.1.2 on 2018-11-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bed_type', models.IntegerField(choices=[(0, 'Others'), (1, 'Operation Room'), (2, 'Intensive Care Unit'), (3, 'Emergency Room'), (4, 'Acute Care Unit'), (5, 'Delivery Floor')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('is_unknown', models.BooleanField(default=True)),
                ('use_custom_setting', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=32)),
                ('device_type', models.CharField(max_length=64)),
                ('recording_type', models.IntegerField(choices=[(1, 'TYPE_WAV'), (2, 'TYPE_NUM'), (3, 'TYPE_IMG'), (5, 'TYPE_STR')], default=2)),
                ('recording_format', models.IntegerField(choices=[(0, 'FMT_NULL'), (1, 'FMT_FLOAT'), (2, 'FMT_DOUBLE'), (3, 'FMT_CHAR'), (4, 'FMT_BYTE'), (5, 'FMT_SHORT'), (6, 'FMT_WORD'), (7, 'FMT_LONG'), (8, 'FMT_DWORD')], default=0)),
                ('unit', models.CharField(max_length=32)),
                ('minval', models.FloatField(default=-100)),
                ('maxval', models.FloatField(default=100)),
                ('color_a', models.PositiveSmallIntegerField(default=255)),
                ('color_r', models.PositiveSmallIntegerField(default=255)),
                ('color_g', models.PositiveSmallIntegerField(default=255)),
                ('color_b', models.PositiveSmallIntegerField(default=255)),
                ('srate', models.FloatField(default=0)),
                ('adc_gain', models.FloatField(default=1.0)),
                ('adc_offset', models.FloatField(default=0.0)),
                ('mon_type', models.IntegerField(choices=[(0, 'UNDEFINED'), (1, 'MON_ECG_WAV'), (2, 'MON_ECG_HR'), (3, 'MON_ECG_PVC'), (4, 'MON_IABP_WAV'), (5, 'MON_IABP_SBP'), (6, 'MON_IABP_DBP'), (7, 'MON_IABP_MBP'), (8, 'MON_PLETH_WAV'), (9, 'MON_PLETH_HR'), (10, 'MON_PLETH_SPO2'), (11, 'MON_RESP_WAV'), (12, 'MON_RESP_RR'), (13, 'MON_CO2_WAV'), (14, 'MON_CO2_RR'), (15, 'MON_CO2_CONC'), (16, 'MON_NIBP_SBP'), (17, 'MON_NIBP_DBP'), (18, 'MON_NIBP_MBP'), (19, 'MON_BT'), (20, 'MON_CVP_WAV'), (21, 'MON_CVP_CVP')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('registered', models.IntegerField(default=0)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sa_api.Bed')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=64, unique=True)),
                ('displayed_name', models.CharField(max_length=64, unique=True)),
                ('is_main', models.BooleanField(default=True)),
                ('use_custom_setting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecorded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('file_path', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sa_api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'device_type')},
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sa_api.Room'),
        ),
    ]
